### ISSUE TITLE
Redirect strategy

### ISSUE THREAD

**Issue by bakura10** [spiffyjr/spiffy-authorize#14]
Hi,

Currently (as it was the case in ZfcRbac), SpiffyAuthorize returns a 403 error when a user is not authorized.

Here is an idea for allowing a redirect strategy:
- Create a new UnauthorizedRedirectStrategy (and maybe rename the current strategy to Unauthorized403Strategy).
- Don't register any strategy by default, it's up to the user to register the strategy he wants.

The UnauthorizedRedirectStrategy would have the following options:
- redirect_route: the name of the route to redirect when a user is not authorized (most of the time it will be "login")
- append_redirect_to: can be either "true" or "false". If true, the previous URL route will be appended in the query param with the "redirectTo" param. For instance, if user try to access to http://www.mysite.com/secret, user will be redirect to the "redirect_route" with the previous route appended, for instance: http://www.mysite.com/login?redirectTo=http://www.mysite.com/secret

What do you think @spiffyjr ?

**Comment by spiffyjr** [comment]
Definitely need a redirect strategy but it's not something at the top of my list right now until a project of mine requires it. Gladly accepting PR's, of course. ;D

**Comment by bakura10** [comment]
Ok, I'll come up with an impl once I've cleaned the whole module :D.

At some point we'll need to refactor the Options module and break it into some smaller sub-options classes I think, otherwise it's gonna be messy.
