### ISSUE TITLE
Some thoughts about ZfcRbac and SpiffyAuthorize

### ISSUE THREAD

**Issue by bakura10** [spiffyjr/spiffy-authorize#5]
Hi,

I just want to share some thoughts about SpiffyAuthorize, which indeed looks very promising.

As I said to @spiffyjr on IRC, we now have three auth modules: ZfcRbac which is targetted to Rbac (and that is a little broken in some edges because iirc at the very beginning it was untetested, so a lot of features are still left not tested), BjyAuthorize for ACL, and this new SpiffyAuthorize that try to unify both.

As I suggested, I think it would be a good idea once this module is stabilized to deprecate ZfcRbac use. It's just going to be a whole mess if you, spiffy, don't maintain ZfcRbac anymore while you're still the owner and author.

On the other hand, I see some problems in this module and I'd like to have your feeling on this:
- The idea of unifying Rbac and ACL is quite appealing, but let's face it, nobody will change from one model to another.
- Nor you and I have any experience in ACL, so any abstractions you try to make both models work in SpiffyAuhtorize, we have no idea if those really work.
- As all ACL users are using BjyAuthorize, I think this module will receive few traction from ACL users, with the risk that the ACL layer is never implemented.

So that lead to my question: shouldn't we, instead, remove SpiffyAuthorize and move it to a refactor branch of ZfcRbac, and ONLY supporting RBAC, as before.

This would make architecture simpler, less maintenance and more contributions as people won't have the feeling that we "abandon" ZfcRbac, but instead made a new version.

What do you think?

**Comment by jmleroux** [comment]
:100: 
I like simple modules that do one job and do it well. Maybe because i'm a linux user : 

The Unix philosophy, originated by Ken Thompson, is a set of cultural norms and philosophical approaches to developing small yet capable software based on the experience of leading developers of the Unix operating system. The Unix philosophy emphasizes building short, simple, clear, modular, and extendable code that can be easily maintained and repurposed by developers other than its creators.

**Comment by spiffyjr** [comment]
I used Zend\Acl for two years prior to writing rbac for ZF2. I have knowledge of Zend\Acl and I think the two systems are similar enough that we can standardize on a single module that is more widely supported and has more features than two individual modules. Things like guards should be able to work with both systems without having to duplicate the guard in two separate modules.

I firmly believe we can have a solid implementation that works with both systems in a single module.

**Comment by spiffyjr** [comment]
Also, you said this module requires doctrine orm but IT DOES NOT. It's only included in the require-dev so that tests pass.

**Comment by bakura10** [comment]
Ok, didn't know that. So to what extents the two models differ ?

I want to trust you, but the question is that BjyAuthorize already has a lot of features and is widely assumed to be the ACL module. Does it still make sense to try to come up with more complex abstractions ?

I just want to ask the question, I don't doubt your skills =).

**Comment by bakura10** [comment]
Oops, my mistake :). going to change that!

**Comment by spiffyjr** [comment]
I haven't looked at BjyAuthorize in a while so I don't know what features it has over this module. ACL and Rbac are somewhat similar and, in fact, ACL can be used like Rbac if you don't use the resource option.

For ACL I believe this is what's needed for SpiffyAuthorize to work:
- The ACL service.
- A provider for resources.
- Likely any fixes in the API that I overlooked when doing them for both ACL/RBAC. isAuthorized() comes to mind for allowing a $resource to be passed.
